### ISSUE TITLE
Please publish unity 5.5.0 with a difference?

### ISSUE THREAD

**Issue by petemounce** [jtcmedia/chocolatey-packages#20]
Hi - I saw in https://github.com/jtcmedia/chocolatey-packages/commit/d9de22174612765fbf866e9f078c627e64109441 that the optional extras could all be installed via `--params /sa /linux /mac /ios` and I took a dependency on that method. However, I hadn't realised that, while the support was present in the package-def in github, that hadn't actually been published to chocolatey.

Would it be possible to publish unity 5.5.0.20170316 (or whatever date - basically using the [package fix version notation](https://github.com/chocolatey/choco/wiki/CreatePackages#package-fix-version-notation)) to give the 5.5.0 package this functionality, please?

**Comment by jtcmedia** [comment]
Just so you know, Chocolatey != Chocolatey.org. Your enterprise can create and host your own Chocolatey repository. If there isn't a demand for this from the community, it shouldn't be hosted on the community repository. Since this is specific to just your organization's needs, I would suggest creating your own packages and hosting them in your organization. In any case, I don't currently have time to do this.

**Comment by petemounce** [comment]
Thanks; that's understood.
