### ISSUE TITLE
Support patch versions

### ISSUE THREAD

**Issue by lambdor** [jtcmedia/chocolatey-packages#24]

**Comment by jtcmedia** [comment]
For something like that, you'd be better off hosting your own packages:
https://chocolatey.org/blog/host-your-own-server

**Comment by lambdor** [comment]
How so? Can't the patch versions be yet another entry in the version history?
```choco install unity --version 5.6.1p1```

**Comment by jtcmedia** [comment]
5d942652c60e959e812a07366ef6b65cff34f525

**Comment by lambdor** [comment]
Could you please also add all historical patch versions.

**Comment by jtcmedia** [comment]
You're welcome to submit PR's to do so. I currently don't have time to go back and do this; I maintain this pkg voluntarily.

**Comment by jtcmedia** [comment]
Actually, PR's won't really help in this case. You'd have to become co-maintainer of the package on chocolatey. You can request to do so on chocolatey.org.

**Comment by lambdor** [comment]
Here is a list of all Unity Win x64 patch releases and there corresponding sha256sums:
[UnitySetup64.links.txt](https://github.com/jtcmedia/chocolatey-packages/files/1397232/UnitySetup64.links.txt)
[UnitySetup64.sha256sums.txt](https://github.com/jtcmedia/chocolatey-packages/files/1397233/UnitySetup64.sha256sums.txt)

The following links are dead:
https://beta.unity3d.com/download/8c9c1a5d2db2/Windows64EditorInstaller/UnitySetup64-5.0.0p3.exe
https://beta.unity3d.com/download/d5a3c6c514e1/Windows64EditorInstaller/UnitySetup64-5.0.1p4.exe

Is this something you can work with?

**Comment by lambdor** [comment]
Here is a zip with multiple chocolateyinstalls.ps1 files populated with the links and SHAs using chocolateyinstalls.ps1 from the 2017.2.0 version as a template:
[chocolateyinstalls.zip](https://github.com/jtcmedia/chocolatey-packages/files/1397567/chocolateyinstalls.zip)

**Comment by lambdor** [comment]
Unity 4 patch versions:
[UnitySetup.links.txt](https://github.com/jtcmedia/chocolatey-packages/files/1398681/UnitySetup.links.txt)
[UnitySetup.sha256sums.txt](https://github.com/jtcmedia/chocolatey-packages/files/1398683/UnitySetup.sha256sums.txt)
[chocolateyinstalls4.zip](https://github.com/jtcmedia/chocolatey-packages/files/1398684/chocolateyinstalls4.zip)

**Comment by lambdor** [comment]
My workflow using Cygwin was as follows.

1. Download all patch release pages and grep them for the links:
```
for i in `seq 1 40`; do wget "https://unity3d.com/unity/qa/patch-releases?page=${i}"; done
for i in *; do cat "${i}" | grep UnitySetup64 >> links5.txt; done
for i in *; do cat "${i}" | grep UnitySetup_update >> links4.txt; done
```

2. Do some manual editing in Notepad++ until the links look like this. Find-and-replace and vertical editing (hold Alt key and select) comes in handy here:
```
wget https://beta.unity3d.com/download/8837012679/UnitySetup_update-4.6.9p4.exe; sha256sum UnitySetup_update-4.6.9p4.exe >> UnitySetup.sha256sums.txt
wget https://beta.unity3d.com/download/8837012679/UnitySetup_update-4.6.9p3.exe; sha256sum UnitySetup_update-4.6.9p3.exe >> UnitySetup.sha256sums.txt
...
```

3. Add the versions, links and sha256sums in LibreOffice and export as .csv with ';' as separator.

4. Copy the chocolateyinstall.ps1 as a template and replace the url and sha256sum with THEURL and THESUM as placeholders.
```
...
$url64              = 'THEURL'
$checksum64         = 'THESUM'
...
```

5. Run the following bash script:
```
#!/bin/bash
for i in $(cat unitys.csv); do
	version="$(cut -d ';' -f 1 <<< "$i")"
	url="$(cut -d ';' -f 2 <<< "$i")"
	sum="$(cut -d ';' -f 3 <<< "$i")"
	echo "$version"
	mkdir -p "$version"
	cp chocolateyinstall.ps1 "$version"
	sed -i "s;THEURL;$url;" "$version/chocolateyinstall.ps1"
	sed -i "s;THESUM;$sum;" "$version/chocolateyinstall.ps1"
done
```

Viola!

**Comment by jtcmedia** [comment]
Just to let you know, this repository is for the chocolately community and although this might be useful for you, legacy patches probably aren't that useful for the community at large so you might just want to put these on your own hosting server: https://chocolatey.org/blog/host-your-own-server

That being said, it looks like you've done most of the legwork and if you are determined to put these on the public repository, request to be added as a co-maintainer of the Unity package.

**Comment by lambdor** [comment]
> this repository is for the chocolately community and although this might be useful for you, legacy patches probably aren't that useful for the community at large

That seems to be an assumption. We are a small company who develop games on our own and usually we have multiple versions installed to check if bugs are solved in version x or appeared in version y. We also do contract work and most of our clients require specific Unity versions. My counter-assumption would be this is the case for most other companies.

That being said, it looks I have requested to be a co-maintainer :)

**Comment by jtcmedia** [comment]
My assumption is based on the fact that the Community repository is not targeted for companies. From https://chocolatey.org/about **"If you are a business looking at using Chocolatey, it is strongly recommended that you do not use the community feed."**

From https://chocolatey.org/faq 
**"Can I use Chocolatey at my organization?
Absolutely! The licensing is very business friendly (plus we have paid options to better help organizations - hint, hint). We typically recommend organizations depending Chocolatey look to managing their own packaging as opposed to using the Community Package Repository (https://chocolatey.org/packages) - packages there are not 100% reliable due to distribution rights with publicly available packages (which causes a major failure point)."**

@ferventcoder would be a good person to talk to about this (although he is very busy).

Note that to be added as a maintainer, you need to contact the Site Admins, not the Package Maintainers.

**Comment by ferventcoder** [comment]
You can host your own packages without cost. If you are doing a lot of testing, you are going to want to set up an internal repo anyway. Otherwise you could end up blocked from the community repository if you are found for excessive use - https://chocolatey.org/docs/community-packages-disclaimer. 

It's probably a great idea to get those packages up, then set up ProGet, Nexus, or Artifactory with a virtual/cached repository for packages to cache down there once from the community repository and then use those local packages instead of hitting the remote repo.

You can also set up MyGet for a hosted solution and have packages cached there from the community repository.

**Comment by ferventcoder** [comment]
Doing that may seem like a little extra work in the beginning, but it will definitely reduce (remove) any down time you would have otherwise later.
