### ISSUE TITLE
Add Unity LTS 2020 and LTS 2019 packages

### ISSUE THREAD

**Issue by doctorpangloss** [jtcmedia/chocolatey-packages#49]
(that is all)

**Comment by jtcmedia** [comment]
Thanks for the issue. This will take a bit of work and I will eventually get around to it but it might not be for some time. You're welcome (or anyone) to submit a PR to get this done quicker.

**Comment by chrisdjali-wrld3d** [comment]
Based on discussion I had with an equivalent issue with Ruby, I think Chocolatey's preferred approach would be to keep a single Unity package, but have the auto-update script detect updates to older Unity versions. A PR implementing that for Ruby is https://github.com/chocolatey-community/chocolatey-packages/pull/1786, so that should provide an outline of how to go about it.
