### ISSUE TITLE
Bitvise SSH Client 9.x was released, but 8.x still on maintain

### ISSUE THREAD

**Issue by RJHsiao** [jtcmedia/chocolatey-packages#56]
Hi there,

Bitvise SSH Client released 9.x this year, the latest version is 9.17[1].
And it looks like the dev team still maintain and release new version for version 8.x[2].

As a suggestion, maybe we can create bitvise-ssh-client-9 for version 9.x, and  create bitvise-ssh-client-8 for version 8.x.
Then we can make bitvise-ssh-client as a meta package that dependence on bitvise-ssh-client-9.
Just looks like [dotnet-runtime](https://community.chocolatey.org/packages/dotnet-runtime) does.

Or, just let user upgrade to 9.x directly.

[1] https://www.bitvise.com/ssh-client-version-history
[2] https://www.bitvise.com/ssh-client-version-history-8

**Comment by jtcmedia** [comment]
For an application that has a linear upgrade path (ex. Bitvise 8 to 9), it is suggested to only use a single package by which Users can [pin](https://docs.chocolatey.org/en-us/choco/commands/pin) the package to stay on earlier releases. [Streams](https://github.com/majkinetor/au/blob/master/README.md#streams) now allows you to have a single package update multiple releases of an application. I suspect dotnet-runtime has multiple packages only because different packages depend on different versions. It's highly unlikely the Chocolatey admins would allow me to release multiple packages for different versions of the same application which isn't a dependency for anything. When I get a chance, I can set up streams for this package so it will update both the 8.x and 9.x releases.
